src/Entity/Proyectos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProyectosRepository")
 */
class Proyectos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $clave_proyecto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_proyecto;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuarios", inversedBy="proyectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $responsable;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ciclos", mappedBy="proyecto")
     */
    private $ciclos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="proyecto")
     */
    private $defectos;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lenguage", inversedBy="proyectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lenguage;

    public function __construct()
    {
        $this->ciclos = new ArrayCollection();
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClaveProyecto(): ?string
    {
        return $this->clave_proyecto;
    }

    public function setClaveProyecto(string $clave_proyecto): self
    {
        $this->clave_proyecto = $clave_proyecto;

        return $this;
    }

    public function getNombreProyecto(): ?string
    {
        return $this->nombre_proyecto;
    }

    public function setNombreProyecto(string $nombre_proyecto): self
    {
        $this->nombre_proyecto = $nombre_proyecto;

        return $this;
    }

    public function getResponsable(): ?Usuarios
    {
        return $this->responsable;
    }

    public function setResponsable(?Usuarios $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    /**
     * @return Collection|Ciclos[]
     */
    public function getCiclos(): Collection
    {
        return $this->ciclos;
    }

    public function addCiclo(Ciclos $ciclo): self
    {
        if (!$this->ciclos->contains($ciclo)) {
            $this->ciclos[] = $ciclo;
            $ciclo->setProyecto($this);
        }

        return $this;
    }

    public function removeCiclo(Ciclos $ciclo): self
    {
        if ($this->ciclos->contains($ciclo)) {
            $this->ciclos->removeElement($ciclo);
            // set the owning side to null (unless already changed)
            if ($ciclo->getProyecto() === $this) {
                $ciclo->setProyecto(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setProyecto($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getProyecto() === $this) {
                $defecto->setProyecto(null);
            }
        }

        return $this;
    }

    public function getLenguage(): ?Lenguage
    {
        return $this->lenguage;
    }

    public function setLenguage(?Lenguage $lenguage): self
    {
        $this->lenguage = $lenguage;

        return $this;
    }
}

src/Entity/Usuarios.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuariosRepository")
 */
class Usuarios
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_usuario;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email_usuario;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Puestos", inversedBy="usuarios")
     * @ORM\JoinColumn(nullable=false)
     */
    private $puesto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Proyectos", mappedBy="responsable")
     */
    private $proyectos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="usuario")
     */
    private $defectos;

    public function __construct()
    {
        $this->proyectos = new ArrayCollection();
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreUsuario(): ?string
    {
        return $this->nombre_usuario;
    }

    public function setNombreUsuario(string $nombre_usuario): self
    {
        $this->nombre_usuario = $nombre_usuario;

        return $this;
    }

    public function getEmailUsuario(): ?string
    {
        return $this->email_usuario;
    }

    public function setEmailUsuario(string $email_usuario): self
    {
        $this->email_usuario = $email_usuario;

        return $this;
    }

    public function getPuesto(): ?Puestos
    {
        return $this->puesto;
    }

    public function setPuesto(?Puestos $puesto): self
    {
        $this->puesto = $puesto;

        return $this;
    }

    /**
     * @return Collection|Proyectos[]
     */
    public function getProyectos(): Collection
    {
        return $this->proyectos;
    }

    public function addProyecto(Proyectos $proyecto): self
    {
        if (!$this->proyectos->contains($proyecto)) {
            $this->proyectos[] = $proyecto;
            $proyecto->setResponsable($this);
        }

        return $this;
    }

    public function removeProyecto(Proyectos $proyecto): self
    {
        if ($this->proyectos->contains($proyecto)) {
            $this->proyectos->removeElement($proyecto);
            // set the owning side to null (unless already changed)
            if ($proyecto->getResponsable() === $this) {
                $proyecto->setResponsable(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setUsuario($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getUsuario() === $this) {
                $defecto->setUsuario(null);
            }
        }

        return $this;
    }
}

src/Form/ProyectosType.php
<?php

namespace App\Form;

use App\Entity\Proyectos;
use App\Entity\Lenguage;
use App\Entity\Usuarios;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bridge\Doctrine\Form\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ProyectosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('clave_proyecto')
            ->add('nombre_proyecto')
            ->add('lenguage', EntityType::class, [
                'class' => Lenguage::class,
                'choice_label' => 'nombreLenguage', 
                   'attr' => ['class' => 'claserow1'],             
        ])

            ->add('responsable', EntityType::class, [
                'class' => Usuarios::class,
                'choice_label' => 'nombreUsuario', 
                   'attr' => ['class' => 'claserow1'],             
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Proyectos::class,
        ]);
    }
}

src/Controller/ProyectosController.php
<?php

namespace App\Controller;

use App\Entity\Proyectos;
use App\Form\ProyectosType;
use App\Repository\ProyectosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/proyectos")
 */
class ProyectosController extends AbstractController
{
    /**
     * @Route("/", name="proyectos_index", methods={"GET"})
     */
    public function index(ProyectosRepository $proyectosRepository): Response
    {
        return $this->render('proyectos/index.html.twig', [
            'proyectos' => $proyectosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="proyectos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $proyecto = new Proyectos();
        $form = $this->createForm(ProyectosType::class, $proyecto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($proyecto);
            $entityManager->flush();

            return $this->redirectToRoute('proyectos_index');
        }

        return $this->render('proyectos/new.html.twig', [
            'proyecto' => $proyecto,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="proyectos_show", methods={"GET"})
     */
    public function show(Proyectos $proyecto): Response
    {
        return $this->render('proyectos/show.html.twig', [
            'proyecto' => $proyecto,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="proyectos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Proyectos $proyecto): Response
    {
        $form = $this->createForm(ProyectosType::class, $proyecto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('proyectos_index');
        }

        return $this->render('proyectos/edit.html.twig', [
            'proyecto' => $proyecto,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="proyectos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Proyectos $proyecto): Response
    {
        if ($this->isCsrfTokenValid('delete'.$proyecto->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($proyecto);
            $entityManager->flush();
        }

        return $this->redirectToRoute('proyectos_index');
    }
}

templates/proyectos/_delete_form.html.twig
<form method="post" action="{{ path('proyectos_delete', {'id': proyecto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ proyecto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/proyectos/_form.html.twig
{{ form_start(form) }}

<style>
    .form-group{
        margin-right: 20px;
        border-radius: 10px;
        border: 1px solid white;
        padding-bottom:8px;
        margin-bottom: 0px;
        font-weight: bold;
    }
    
    label{
        color:#455A64!important;
        padding-left: 10px;
    }
    
    #hallazgos_descripcion{
        height: 60px;
        padding-left:0px;
        margin-left: -10px;
    }
    
    .iconcalendar{
        margin-left:-27px;
        margin-top:26px;
        height: 34px;
    }
    .iconcalendar2{
        margin-left:31%;
        margin-top:26px;
        height: 34px;
    }
    #defectos_evidencia{
        width: 320%;
    }
    .form-group{
        border:none!important;
    }
    #proyectos_clave_proyecto, #proyectos_nombre_proyecto, #proyectos_lenguage, #proyectos_responsable {
        font-size:12.5px;
    }
</style>

<div class="container">
<div class="row" style="padding-left:17px; margin-right:16px;  font-size:12px;">
	    {{form_row(form.clave_proyecto)}}
	
</div>
<div class="row" style="padding-left:15px; margin-right:6px;  font-size:12px;">
	   {{form_row(form.nombre_proyecto  )}}
</div>
<div class="row" style="padding-left:17px; margin-right:16px;  font-size:12px;">
	    {{form_row(form.lenguage)}}
	     {{form_row(form.responsable)}}
</div>

<br>
<a class="btn" href="{{ path('proyectos_index') }}" style="color:#2c3e50;"><i class="fas fa-chevron-left fa-2x"></i></a>
<button class="btn shadow" 
style="background-color:#4C4C71; border:none; color:white; border-radius:0px; font-size:13.6px;">
{{ button_label|default('Guardar proyecto') }}</button>

</div>



{{ form_end(form) }}

templates/proyectos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Proyectos{% endblock %}

{% block body %}
    <h1>Edit Proyectos</h1>

    {{ include('proyectos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('proyectos_index') }}">back to list</a>

    {{ include('proyectos/_delete_form.html.twig') }}
{% endblock %}

templates/proyectos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SQA | Proyectos{% endblock %}

    {% block body %}
        <style>
        .encabezadot{
            background-color: #4C4C71;
            color:white;
            font-weight: lighter;
        }
        .body{
            font-size: 11px;
        }
        .btnnuevo{
            background-color: #666699;
            border-radius:0px;
            color:white;
            font-size: 12px;
            padding-left: 5px;
        }
        .btnsecundario{
            background-color: #546E7A;
            border-radius:0px;
            color:white;
            font-size: 12px;
            padding-left: 5px;
        }
        .badge{
            border-radius:0px;
        }
        th{
            font-size: 13px; font-weight:lighter;
        }
        .izquierdo{
            padding-right: 0px;
            padding-left: 0px;
        }
        .derecho{
            padding-left: 0px;
            padding-right: 0px;
        }
        .list-group{
            border-radius: none;
        }
        .list-group-item{
            padding-bottom: 2px;
        }
        .enlistabtn{
            background-color: #666699;
            padding:5px;
            padding-right: 10px;
            margin:0px;
            border:none;
            color:white;
            width: 130px;
        }
        #segundaVistadiv{
            display: none;
        }
        #terceraVistadiv{
            background-color: yellow;
            display: none;
        }
       

        </style>






    <div style="background-color:#666699; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">
    </div><br>
     

    <div class="container-fluid">
       <h4>| Proyectos</h4>
            <p style="font-size:12.5px; color:#455A64;"><i class="fas fa-info-circle" style="font-size:15px; color:#e67e22;"> </i> Información de todos los proyectos registrados en <strong>Simetrical</strong> </p>

            <div style="padding-bottom:10px; text-align:right;">
                <a href="{{ path('proyectos_new') }}" class="btn btnnuevo shadow" style="color:white;"><i class="fas fa-plus"> </i>  Nuevo Registro</a>
            </div>





    <div class="container-fluid" >
        <div class="row">
            <div class="col" style="font-size:13px; ">
                <!-- contenido panel 1-->
                <ul class="list-group list-group-flush shadow" >
                    <li class="list-group-item " style="background-color:#666699;"><button class="enlistabtn" id="vistaGeneralbtn"><i class="fas fa-project-diagram" style="font-size:16px;"></i> Vista General</button></li>
                    <li class="list-group-item" style="background-color:#666699;"><button class="enlistabtn" id="segundaVistabtn"><i class="fas fa-laptop-code" style="font-size:16px;"></i> Por Framework</button></li>
                    <li class="list-group-item " style="background-color:#666699;"><button class="enlistabtn"  id="terceraVistabtn"><i class="fas fa-walking" style="font-size:16px;"></i> Por Responsable</button></li>
                    <li class="list-group-item disabled" style="background-color:#666699;">Opcion 4</li>
                    <li class="list-group-item disabled" style="background-color:#666699;">Opcion 5</li>
                </ul>



                <!-- fin panel 1 -->
            </div>

            <div class="col-10 shadow" style="padding: 0px;" id="vistaGeneraldiv">
                <!-- contenido planel 2-->
                <table class="table highchart table-ligth table-hover" style="font-size: 12px;">
                    <thead class="thead encabezadot">
                        <tr>
                            <th>ID</th>
                            <th>Clave de proyecto</th>
                            <th>Nombre</th>
                            <th>Responsable</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for proyecto in proyectos %}
                            <tr>
                                <td>{{ proyecto.id }}</td>
                                <td style="font-weight:bold;">{{ proyecto.claveProyecto }}</td>
                                <td>{{ proyecto.nombreProyecto }}</td>

                                <td>{{ proyecto.responsable.nombreUsuario }}</td>

                                <td>
                                    <a href="{{ path('proyectos_show', {'id': proyecto.id}) }}"><i class="fas fa-eye fa-2x" style="color:#0091EA;"></i></a>
                                    <a href="{{ path('proyectos_edit', {'id': proyecto.id}) }}"><i class="fas fa-highlighter" style="color:#0277BD; font-size:15px;"></i></a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4">no records found</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>


                <!-- cierre panel 2-->
            </div> <!-- cierra div vistaGeneral -->

            <div class="col-10 shadow" style="padding: 0px; align-items:center;" id="segundaVistadiv"><br>
                <p>Indicadores de grafica 1 </p> <br>
                <div id="chartdiv" style="width:60%; height:280px;" class="container"></div>
            </div> <!-- cierra div secundaVista -->
            <div class="col-10 shadow" style="padding: 0px;" id="terceraVistadiv">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae inventore tenetur velit ducimus explicabo architecto expedita quidem labore quibusdam reprehenderit aliquam accusamus cumque iure adipisci dicta, culpa sunt? Consequatur, sit.</p>
            </div> <!-- cierra div secundaVista -->
        </div>
    </div>
</div>






{% endblock %}

templates/proyectos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Proyectos{% endblock %}

	{% block body %}

		<div style="background-color:#666699; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">
		</div><br>

		<div class="container" style="padding-top:1px; border-left: 4px solid #4C4C71;">
			<h4>Nuevo proyecto</h4>
			<p style="font-size:12.5px; color:gray;"><strong> Por favor, ingrese los datos del proyecto:</strong>  </p>
			<br>
			{{ include('proyectos/_form.html.twig') }}


		{% endblock %}

templates/proyectos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Proyectos{% endblock %}

{% block body %}
    <h1>Proyectos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ proyecto.id }}</td>
            </tr>
            <tr>
                <th>Clave_proyecto</th>
                <td>{{ proyecto.claveProyecto }}</td>
            </tr>
            <tr>
                <th>Nombre_proyecto</th>
                <td>{{ proyecto.nombreProyecto }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('proyectos_index') }}">back to list</a>

    <a href="{{ path('proyectos_edit', {'id': proyecto.id}) }}">edit</a>

    {{ include('proyectos/_delete_form.html.twig') }}
{% endblock %}