src/Entity/Ciclos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CiclosRepository")
 */
class Ciclos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_ciclo;

    /**
     * @ORM\Column(type="date")
     */
    private $f_ini_prog;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $f_ini_real;

    /**
     * @ORM\Column(type="date")
     */
    private $f_fin_prog;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $f_fin_real;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Proyectos", inversedBy="ciclos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $proyecto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="ciclo")
     */
    private $defectos;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $estatusCiclo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duracionCiclos;


    public function __construct()
    {
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreCiclo(): ?string
    {
        return $this->nombre_ciclo;
    }

    public function setNombreCiclo(string $nombre_ciclo): self
    {
        $this->nombre_ciclo = $nombre_ciclo;

        return $this;
    }

    public function getFIniProg(): ?\DateTimeInterface
    {
        return $this->f_ini_prog;
    }

    public function setFIniProg(\DateTimeInterface $f_ini_prog): self
    {
        $this->f_ini_prog = $f_ini_prog;

        return $this;
    }

    public function getFIniReal(): ?\DateTimeInterface
    {
        return $this->f_ini_real;
    }

    public function setFIniReal(?\DateTimeInterface $f_ini_real): self
    {
        $this->f_ini_real = $f_ini_real;

        return $this;
    }

    public function getFFinProg(): ?\DateTimeInterface
    {
        return $this->f_fin_prog;
    }

    public function setFFinProg(\DateTimeInterface $f_fin_prog): self
    {
        $this->f_fin_prog = $f_fin_prog;

        return $this;
    }

    public function getFFinReal(): ?\DateTimeInterface
    {
        return $this->f_fin_real;
    }

    public function setFFinReal(?\DateTimeInterface $f_fin_real): self
    {
        $this->f_fin_real = $f_fin_real;

        return $this;
    }

    public function getProyecto(): ?Proyectos
    {
        return $this->proyecto;
    }

    public function setProyecto(?Proyectos $proyecto): self
    {
        $this->proyecto = $proyecto;

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setCiclo($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getCiclo() === $this) {
                $defecto->setCiclo(null);
            }
        }

        return $this;
    }

    public function getEstatusCiclo(): ?string
    {
        return $this->estatusCiclo;
    }

    public function setEstatusCiclo(?string $estatusCiclo): self
    {
        $this->estatusCiclo = $estatusCiclo;

        return $this;
    }

    public function getDuracionCiclos(): ?int
    {
        return $this->duracionCiclos;
    }

    public function setDuracionCiclos(?int $duracionCiclos): self
    {
        $this->duracionCiclos = $duracionCiclos;

        return $this;
    }

}

src/Entity/Proyectos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProyectosRepository")
 */
class Proyectos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $clave_proyecto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_proyecto;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuarios", inversedBy="proyectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $responsable;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ciclos", mappedBy="proyecto")
     */
    private $ciclos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="proyecto")
     */
    private $defectos;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lenguage", inversedBy="proyectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lenguage;

    public function __construct()
    {
        $this->ciclos = new ArrayCollection();
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClaveProyecto(): ?string
    {
        return $this->clave_proyecto;
    }

    public function setClaveProyecto(string $clave_proyecto): self
    {
        $this->clave_proyecto = $clave_proyecto;

        return $this;
    }

    public function getNombreProyecto(): ?string
    {
        return $this->nombre_proyecto;
    }

    public function setNombreProyecto(string $nombre_proyecto): self
    {
        $this->nombre_proyecto = $nombre_proyecto;

        return $this;
    }

    public function getResponsable(): ?Usuarios
    {
        return $this->responsable;
    }

    public function setResponsable(?Usuarios $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    /**
     * @return Collection|Ciclos[]
     */
    public function getCiclos(): Collection
    {
        return $this->ciclos;
    }

    public function addCiclo(Ciclos $ciclo): self
    {
        if (!$this->ciclos->contains($ciclo)) {
            $this->ciclos[] = $ciclo;
            $ciclo->setProyecto($this);
        }

        return $this;
    }

    public function removeCiclo(Ciclos $ciclo): self
    {
        if ($this->ciclos->contains($ciclo)) {
            $this->ciclos->removeElement($ciclo);
            // set the owning side to null (unless already changed)
            if ($ciclo->getProyecto() === $this) {
                $ciclo->setProyecto(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setProyecto($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getProyecto() === $this) {
                $defecto->setProyecto(null);
            }
        }

        return $this;
    }

    public function getLenguage(): ?Lenguage
    {
        return $this->lenguage;
    }

    public function setLenguage(?Lenguage $lenguage): self
    {
        $this->lenguage = $lenguage;

        return $this;
    }
}

src/Form/CiclosType.php
<?php

namespace App\Form;

use App\Entity\Ciclos;
use App\Entity\Proyectos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bridge\Doctrine\Form\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CiclosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('nombre_ciclo')
        ->add('proyecto', EntityType::class, [
            'class' => Proyectos::class,
            'choice_label' => 'nombreProyecto', 
            'attr' => ['class' => 'claserow1'],             
        ])
        ->add('f_ini_prog', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'js-datepicker claserow1 input-group-prepend'],
                
            ])
        ->add('f_ini_real', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'js-datepicker claserow1 input-group-prepend'],
                
            ])
        ->add('f_fin_prog', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'js-datepicker claserow1 input-group-prepend'],
                
            ])
        ->add('f_fin_real', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'js-datepicker claserow1 input-group-prepend'],
                
            ])

        ->add('estatusCiclo', ChoiceType::class, [
            'choices' => [
                'Seleccione el estatus del request' => null,
                'Sin iniciar' => 'Sin iniciar',
                'Iniciado' => 'Iniciado',
                'Cancelado' => 'Cancelado',
                'Finalizado' => 'Finalizado'
            ],
                'attr' => ['class' => 'claserow1'],

        ])
        ->add('duracionCiclos', null, [
                'attr' => ['class' => 'example', 'readonly' => 'readonly', 'value' => '0'], 
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ciclos::class,
        ]);
    }
}

src/Controller/CiclosController.php
<?php

namespace App\Controller;

use App\Entity\Ciclos;
use App\Form\CiclosType;
use App\Repository\CiclosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ciclos")
 */
class CiclosController extends AbstractController
{
    /**
     * @Route("/", name="ciclos_index", methods={"GET"})
     */
    public function index(CiclosRepository $ciclosRepository): Response
    {
        $ciclosTotales = $ciclosRepository->obtieneCiclosTotal();
        $proyectosCiclos = $ciclosRepository->obtieneProyectosDeCiclos();
        $ciclosFinalizados = $ciclosRepository->obtieneCiclosFinalizados();
        $ciclosEmpezados = $ciclosRepository->obtieneCiclosEmpezados();
        $duracionCiclos = $ciclosRepository->obtieneDuracionCiclos();

        return $this->render('ciclos/index.html.twig', [
            'ciclos' => $ciclosRepository->findAll(),
            'totales' => $ciclosTotales,
            'proyectos' => $proyectosCiclos,
            'finalizados' => $ciclosFinalizados,
            'empezados' => $ciclosEmpezados,
            'duracion' => $duracionCiclos,
        ]);
    }

    /**
     * @Route("/new", name="ciclos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ciclo = new Ciclos();
        $form = $this->createForm(CiclosType::class, $ciclo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ciclo);
            $entityManager->flush();

            return $this->redirectToRoute('ciclos_index');
        }

        return $this->render('ciclos/new.html.twig', [
            'ciclo' => $ciclo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ciclos_show", methods={"GET"})
     */
    public function show(Ciclos $ciclo): Response
    {
        return $this->render('ciclos/show.html.twig', [
            'ciclo' => $ciclo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ciclos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ciclos $ciclo): Response
    {
        $form = $this->createForm(CiclosType::class, $ciclo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ciclos_index');
        }

        return $this->render('ciclos/edit.html.twig', [
            'ciclo' => $ciclo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ciclos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ciclos $ciclo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ciclo->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ciclo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ciclos_index');
    }
}

templates/ciclos/_delete_form.html.twig
<form method="post" action="{{ path('ciclos_delete', {'id': ciclo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ciclo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ciclos/_form.html.twig
{{ form_start(form) }}

<style>
    .form-group{
        margin-right: 20px;
        border-radius: 10px;
        border: 1px solid white;
        padding-bottom:8px;
        margin-bottom: 0px;
        font-weight: bold;
    }
    
    label{
        color:#455A64!important;
        padding-left: 10px;
    }
    
    #hallazgos_descripcion{
        height: 60px;
        padding-left:0px;
        margin-left: -10px;
    }
    
    .iconcalendar{
        margin-left:-27px;
        margin-top:28px;
        height: 33px;
    }
</style>



    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ciclos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ciclos{% endblock %}

{% block body %}
    <h1>Edit Ciclos</h1>

    {{ include('ciclos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ciclos_index') }}">back to list</a>

    {{ include('ciclos/_delete_form.html.twig') }}
{% endblock %}

templates/ciclos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ciclos index{% endblock %}

  {% block body %}
   <style>
   .encabezadot{
    background-color: #4C4C71;
    color:white;
    font-weight: lighter;
  }
  .body{
    font-size: 11px;
  }
  .card-body{
    padding-left: 12px;
  }
  .btnnuevo{
    background-color: #666699;
    border-radius:0px;
    color:white;
    font-size: 11px;
    padding-left: 5px;
  }
  .btnsecundario{
    background-color: #546E7A;
    border-radius:0px;
    color:white;
    font-size: 12px;
    padding-left: 5px;
  }
  .badge{
    border-radius:0px;
  }
  th{
    font-size: 12px; font-weight:lighter;
  }
  .izquierdo{
    padding-right: 0px;
    padding-left: 0px;
  }
  .derecho{
    padding-left: 0px;
    padding-right: 0px;
  }
  .list-group{
    border-radius: none;
  }
  .list-group-item, .show{
    border-radius: none;
    border:none;
  }
  #boton12:hover{
    background-color:#414161;
    color: white;
  }
  .pcard{
    margin-bottom: 1px;
    font-size: 10.5px;
    text-align: left;
  }
  .pcard2{
   margin-bottom: 1px;
   font-size: 10.5px;
   text-align: left;
   margin-top:18px;
 }
 .circulocolor{
  font-size:7px;
  padding-right: 3px;
  text-align: right;
}

h4{
  color: #2c3e50;
}


</style>
<div style="background-color:#666699; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">

</div><br>

<div class="container-fluid">

  <h4>Requests | Ciclos</h4>
  <p style="font-size:12.5px; color:#455A64;"><i class="fas fa-info-circle" style="font-size:15px; color:#e67e22;"> </i> 
    <strong>Ciclos de prueba</strong> son definiciones de los Request o Sprints, que, depende la metodología utilizada en los proyectos se asigna a una revisión de<strong> SQA</strong> </p><br>



    <div class="row" style="color:white;">

      <div class="col">
        <div class="card" style="background-color:#ECEFF1; border:none;">
          <div class="card-body" style="padding-bottom:1px;">
            <div class="row">
             <div class="col-sm-3" style="padding:2px;">
              <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters shadow" style="background-color:#414161;">
                  <div class="col-md-4" style="justify-content:center; align-items:center; display:flex; padding-left:5px; padding-right:5px;">
                    <h1 style="font-size:2.5vw; margin:5px;">{{totales}}</h1>
                  </div>
                  <div class="col-md-8">
                    <div class="card-body" style="padding:2px;">
                      <p class="card-title" style="font-size:14px; margin-bottom:3px;"><strong>General</strong></p>
                      <p class="card-text" style="font-size:12px; color:#ECEFF1">
                        <p class="pcard"><i class="fas fa-circle circulocolor" style="color:#FAFAFA;"></i><strong>0</strong> Sin iniciar </p>
                        <p class="pcard"><i class="fas fa-circle circulocolor" style="color:#00E5FF;"></i><strong>{{empezados}}</strong> Iniciados </p>
                        <p class="pcard"><i class="fas fa-circle circulocolor" style="color:#e67e22;"></i><strong>0</strong> Cancelados </p>
                        <p class="pcard"> <i class="fas fa-circle circulocolor" style="color:#00E676;"></i><strong>{{finalizados}}</strong> Finalizados</p>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-3" style="padding:2px;">
             <div class="card mb-3" style="max-width: 540px;">
              <div class="row no-gutters shadow" style="background-color:#414161;">
                <div class="col-md-4" style="justify-content:center; align-items:center; display:flex; padding-left:5px; padding-right:5px;">
                  <h1 style="font-size:2.5vw; margin:5px;">3</h1>
                </div>
                <div class="col-md-8">
                  <div class="card-body" style="padding:2px;">
                    <p class="card-title" style="font-size:14px; margin-bottom:3px;"><strong>Proyectos</strong></p>
                    <p class="card-text" style="font-size:12px; color:#0077B5">
                      <p class="pcard">Proyectos distint.</p>
                      <p class="pcard" style="color:#414161;">____________________</p>
                      <p class="pcard"><strong>1.3</strong> Promedio</p>
                      <p class="pcard">Proy/Request</p>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-3" style="padding:2px;">
           <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters shadow" style="background-color:#414161;">
              <div class="col-md-4" style="justify-content:center; align-items:center; display:flex; padding-left:5px; padding-right:5px;">
                <h1 style="font-size:2.5vw; margin:5px; text-align:right;">1.3</h1>
              </div>
              <div class="col-md-8">
                <div class="card-body" style="padding:2px;">
                  <p class="card-title" style="font-size:14px; margin-bottom:3px;"><strong>Duraciones</strong></p>
                  <p class="card-text" style="font-size:12px; color:#0077B5">
                    <p class="pcard">Días prom/Request</p>
                    <p class="pcard" style="color:#414161;">____________________</p>
                    <p class="pcard"> Mayor: <strong>{{finalizados}}</strong> días <i class="fas fa-sort-up" style="color:#FF6D00;"></i></p>
                    <p class="pcard"> Menor: <strong>{{finalizados}}</strong> días <i class="fas fa-sort-down" style="color:#00BCD4;"></i></p>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-3" style="padding:2px;">
         <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters shadow" style="background-color:#414161;">
            <div class="col-md-4" style="justify-content:center; align-items:center; display:flex; padding-left:5px; padding-right:5px;">
              <h1 style="font-size:2.5vw; margin:5px;">4</h1>
            </div>
            <div class="col-md-8">
              <div class="card-body" style="padding:2px;">
                <p class="card-title" style="font-size:14px; margin-bottom:3px;"><strong>Nuevos</strong></p>
                <p class="card-text" style="font-size:12px; color:#ECEFF1">
                  <p class="pcard">Prom News/Mes</p>
                  <p class="pcard" style="color:#414161;">____________________</p>
                  <p class="pcard"><strong>1.3</strong> Prom de</p>
                  <p class="pcard">Proyectos / Request</p>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<div class="col">
  <div class="chart-container" style="position: relative; height:154px; width:90%; text-align:center;">
   <canvas id="myChart"></canvas>
 </div>



</div>
</div>



<div style="padding-bottom:5px; padding-top:15px; align-items:center; text-align:right;">
  <a href="{{ path('ciclos_new') }}" class="btn btnnuevo shadow" id="boton12" style="font-size:12px; margin-right:6px;">| Registrar nuevo Request</a>
</div>


<table class="table table-ligth table-hover" style="font-size: 12px;" id="tablaCiclos">
  <thead class="thead encabezadot">
    <tr>
      <th>Id</th>
      <th>Nombre del ciclo</th>
      <th>Inicio programado</th>
      <th>Inicio real</th>
      <th>Fin programado</th>
      <th>Fin real</th>
      <th>Proyecto</th>
      <th>Estatus</th>
      <th>Duración</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for ciclo in ciclos %}
      <tr>
        <td>{{ ciclo.id }}</td>
        <td>{{ ciclo.nombreCiclo }}</td>
        <td>{{ ciclo.fIniProg ? ciclo.fIniProg|date('Y-m-d') : '' }}</td>

        {%  if ciclo.fIniReal == ''  %}
        <td style="width:6%; font-size:13px;"> <span class="badge shadow" style="background-color:gray;color:White; padding:4px;">Sin datos</span></td>
      {% else %}
        <td><span class="badge badge-info" style="background-color:#7986CB;">{{ ciclo.fIniReal ? ciclo.fIniReal|date('Y-m-d') : '' }}</span></td>

      {% endif %}




      <td>{{ ciclo.fFinProg ? ciclo.fFinProg|date('Y-m-d') : '' }}</td>

      {%  if ciclo.fFinReal == ''  %}
      <td style="width:6%; font-size:13px;"> <span class="badge shadow" style="background-color:gray;color:White; padding:4px;">Sin datos</span></td>
    {% else %}
      <td><span class="badge badge-info" style="background-color:#7986CB;">{{ ciclo.fFinReal ? ciclo.fFinReal|date('Y-m-d') : '' }}</span></td>

    {% endif %}

    <td>{{ ciclo.proyecto.nombreProyecto }}</td>
    

    {% if ciclo.estatusCiclo == "Finalizado"    %}
     <td><i class="fas fa-circle circulocolor" style="color:#00E676; font-size:12px;"></i> {{ ciclo.estatusCiclo}}</td>
     <td>{{ciclo.duracionCiclos}}</td>
   {% elseif ciclo.estatusCiclo == "Cancelado" %}
      <td><i class="fas fa-circle circulocolor" style="color:#e67e22; font-size:12px;"></i> {{ ciclo.estatusCiclo}}</td>
     <td>{{ciclo.duracionCiclos}}</td>
   {% elseif ciclo.estatusCiclo == "Iniciado" %}
        <td><i class="fas fa-circle circulocolor" style="color:#00E5FF; font-size:12px;"></i> {{ ciclo.estatusCiclo}}</td>
     <td>{{ciclo.duracionCiclos}}</td>
   {% else %}
    <td><i class="fas fa-circle circulocolor" style="color:#FAFAFA; font-size:12px;"></i>{{ ciclo.estatusCiclo}}</td>
    <td>{{ ciclo.duracionCiclos}}</td>
  {% endif %}


  <td>
    <a href="{{ path('ciclos_show', {'id': ciclo.id}) }}"><i class="fas fa-eye fa-2x" style="color:#0091EA;"></i></a>
    <a href="{{ path('ciclos_edit', {'id': ciclo.id}) }}"><i class="fas fa-highlighter" style="color:#0277BD; font-size:15px;"></i></a>
  </td>
</tr>
{% else %}
  <tr>
    <td colspan="7">no records found</td>
  </tr>
{% endfor %}
</tbody>
</table>



</div>








{% endblock %}

templates/ciclos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ciclos{% endblock %}

{% block body %}
  <div style="background-color:#78909C; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">
      <p style="font-size:14px; margin-bottom:4px;"> <i class="fas fa-project-diagram"></i>  Registro de Requests entrante</p>

    </div><br>

    <div class="container" style="padding-top:1px; border-left: 4px solid #2f245d;">
            <p style="font-size:12.5px; color:gray;"><strong> Datos que tendrá la incidencia a crear:</strong>  </p>

  
{{ include('ciclos/_form.html.twig') }}

  
    </div>
{% endblock %}

templates/ciclos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ciclos{% endblock %}

{% block body %}
    <h1>Ciclos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ciclo.id }}</td>
            </tr>
            <tr>
                <th>Nombre_ciclo</th>
                <td>{{ ciclo.nombreCiclo }}</td>
            </tr>
            <tr>
                <th>F_ini_prog</th>
                <td>{{ ciclo.fIniProg ? ciclo.fIniProg|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>F_ini_real</th>
                <td>{{ ciclo.fIniReal ? ciclo.fIniReal|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>F_fin_prog</th>
                <td>{{ ciclo.fFinProg ? ciclo.fFinProg|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>F_fin_real</th>
                <td>{{ ciclo.fFinReal ? ciclo.fFinReal|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ciclos_index') }}">back to list</a>

    <a href="{{ path('ciclos_edit', {'id': ciclo.id}) }}">edit</a>

    {{ include('ciclos/_delete_form.html.twig') }}
{% endblock %}