src/Entity/Puestos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PuestosRepository")
 */
class Puestos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_puesto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Usuarios", mappedBy="puesto")
     */
    private $usuarios;

    public function __construct()
    {
        $this->usuarios = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombrePuesto(): ?string
    {
        return $this->nombre_puesto;
    }

    public function setNombrePuesto(string $nombre_puesto): self
    {
        $this->nombre_puesto = $nombre_puesto;

        return $this;
    }

    /**
     * @return Collection|Usuarios[]
     */
    public function getUsuarios(): Collection
    {
        return $this->usuarios;
    }

    public function addUsuario(Usuarios $usuario): self
    {
        if (!$this->usuarios->contains($usuario)) {
            $this->usuarios[] = $usuario;
            $usuario->setPuesto($this);
        }

        return $this;
    }

    public function removeUsuario(Usuarios $usuario): self
    {
        if ($this->usuarios->contains($usuario)) {
            $this->usuarios->removeElement($usuario);
            // set the owning side to null (unless already changed)
            if ($usuario->getPuesto() === $this) {
                $usuario->setPuesto(null);
            }
        }

        return $this;
    }

}

src/Entity/Usuarios.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuariosRepository")
 */
class Usuarios
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_usuario;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email_usuario;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Puestos", inversedBy="usuarios")
     * @ORM\JoinColumn(nullable=false)
     */
    private $puesto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Proyectos", mappedBy="responsable")
     */
    private $proyectos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="usuario")
     */
    private $defectos;

    public function __construct()
    {
        $this->proyectos = new ArrayCollection();
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreUsuario(): ?string
    {
        return $this->nombre_usuario;
    }

    public function setNombreUsuario(string $nombre_usuario): self
    {
        $this->nombre_usuario = $nombre_usuario;

        return $this;
    }

    public function getEmailUsuario(): ?string
    {
        return $this->email_usuario;
    }

    public function setEmailUsuario(string $email_usuario): self
    {
        $this->email_usuario = $email_usuario;

        return $this;
    }

    public function getPuesto(): ?Puestos
    {
        return $this->puesto;
    }

    public function setPuesto(?Puestos $puesto): self
    {
        $this->puesto = $puesto;

        return $this;
    }

    /**
     * @return Collection|Proyectos[]
     */
    public function getProyectos(): Collection
    {
        return $this->proyectos;
    }

    public function addProyecto(Proyectos $proyecto): self
    {
        if (!$this->proyectos->contains($proyecto)) {
            $this->proyectos[] = $proyecto;
            $proyecto->setResponsable($this);
        }

        return $this;
    }

    public function removeProyecto(Proyectos $proyecto): self
    {
        if ($this->proyectos->contains($proyecto)) {
            $this->proyectos->removeElement($proyecto);
            // set the owning side to null (unless already changed)
            if ($proyecto->getResponsable() === $this) {
                $proyecto->setResponsable(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setUsuario($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getUsuario() === $this) {
                $defecto->setUsuario(null);
            }
        }

        return $this;
    }
}

src/Form/UsuariosType.php
<?php

namespace App\Form;

use App\Entity\Usuarios;
use App\Entity\Puestos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bridge\Doctrine\Form\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UsuariosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre_usuario')
            ->add('email_usuario')
            ->add('puesto', EntityType::class, [
                'class' => Puestos::class,
                'choice_label' => 'nombrePuesto', 
                   'attr' => ['class' => 'claserow1'],             
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Usuarios::class,
        ]);
    }
}

src/Controller/UsuariosController.php
<?php

namespace App\Controller;

use App\Entity\Usuarios;
use App\Form\UsuariosType;
use App\Repository\UsuariosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/usuarios")
 */
class UsuariosController extends AbstractController
{
    /**
     * @Route("/", name="usuarios_index", methods={"GET"})
     */
    public function index(UsuariosRepository $usuariosRepository): Response
    {
        return $this->render('usuarios/index.html.twig', [
            'usuarios' => $usuariosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="usuarios_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $usuario = new Usuarios();
        $form = $this->createForm(UsuariosType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($usuario);
            $entityManager->flush();

            return $this->redirectToRoute('usuarios_index');
        }

        return $this->render('usuarios/new.html.twig', [
            'usuario' => $usuario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="usuarios_show", methods={"GET"})
     */
    public function show(Usuarios $usuario): Response
    {
        return $this->render('usuarios/show.html.twig', [
            'usuario' => $usuario,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="usuarios_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Usuarios $usuario): Response
    {
        $form = $this->createForm(UsuariosType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('usuarios_index');
        }

        return $this->render('usuarios/edit.html.twig', [
            'usuario' => $usuario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="usuarios_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Usuarios $usuario): Response
    {
        if ($this->isCsrfTokenValid('delete'.$usuario->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($usuario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('usuarios_index');
    }
}

templates/usuarios/_delete_form.html.twig
<form method="post" action="{{ path('usuarios_delete', {'id': usuario.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
    <button class="btn">Delete</button>
</form>

templates/usuarios/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/usuarios/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Usuarios{% endblock %}

{% block body %}
    <h1>Edit Usuarios</h1>

    {{ include('usuarios/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('usuarios_index') }}">back to list</a>

    {{ include('usuarios/_delete_form.html.twig') }}
{% endblock %}

templates/usuarios/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuarios index{% endblock %}

{% block body %}
    <h1>Usuarios index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre_usuario</th>
                <th>Email_usuario</th>
                <th>Puesto</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.id }}</td>
                <td>{{ usuario.nombreUsuario }}</td>
                <td>{{ usuario.emailUsuario }}</td>
                <td>{{ usuario.puesto.nombrePuesto }}</td>
                <td>
                    <a href="{{ path('usuarios_show', {'id': usuario.id}) }}">show</a>
                    <a href="{{ path('usuarios_edit', {'id': usuario.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('usuarios_new') }}">Create new</a>
{% endblock %}

templates/usuarios/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Usuarios{% endblock %}

{% block body %}
    <h1>Create new Usuarios</h1>

    {{ include('usuarios/_form.html.twig') }}

    <a href="{{ path('usuarios_index') }}">back to list</a>
{% endblock %}

templates/usuarios/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuarios{% endblock %}

{% block body %}
    <h1>Usuarios</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ usuario.id }}</td>
            </tr>
            <tr>
                <th>Nombre_usuario</th>
                <td>{{ usuario.nombreUsuario }}</td>
            </tr>
            <tr>
                <th>Email_usuario</th>
                <td>{{ usuario.emailUsuario }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('usuarios_index') }}">back to list</a>

    <a href="{{ path('usuarios_edit', {'id': usuario.id}) }}">edit</a>

    {{ include('usuarios/_delete_form.html.twig') }}
{% endblock %}