src/Entity/Ciclos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CiclosRepository")
 */
class Ciclos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_ciclo;

    /**
     * @ORM\Column(type="date")
     */
    private $f_ini_prog;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $f_ini_real;

    /**
     * @ORM\Column(type="date")
     */
    private $f_fin_prog;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $f_fin_real;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Proyectos", inversedBy="ciclos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $proyecto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="ciclo")
     */
    private $defectos;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $estatusCiclo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duracionCiclos;


    public function __construct()
    {
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreCiclo(): ?string
    {
        return $this->nombre_ciclo;
    }

    public function setNombreCiclo(string $nombre_ciclo): self
    {
        $this->nombre_ciclo = $nombre_ciclo;

        return $this;
    }

    public function getFIniProg(): ?\DateTimeInterface
    {
        return $this->f_ini_prog;
    }

    public function setFIniProg(\DateTimeInterface $f_ini_prog): self
    {
        $this->f_ini_prog = $f_ini_prog;

        return $this;
    }

    public function getFIniReal(): ?\DateTimeInterface
    {
        return $this->f_ini_real;
    }

    public function setFIniReal(?\DateTimeInterface $f_ini_real): self
    {
        $this->f_ini_real = $f_ini_real;

        return $this;
    }

    public function getFFinProg(): ?\DateTimeInterface
    {
        return $this->f_fin_prog;
    }

    public function setFFinProg(\DateTimeInterface $f_fin_prog): self
    {
        $this->f_fin_prog = $f_fin_prog;

        return $this;
    }

    public function getFFinReal(): ?\DateTimeInterface
    {
        return $this->f_fin_real;
    }

    public function setFFinReal(?\DateTimeInterface $f_fin_real): self
    {
        $this->f_fin_real = $f_fin_real;

        return $this;
    }

    public function getProyecto(): ?Proyectos
    {
        return $this->proyecto;
    }

    public function setProyecto(?Proyectos $proyecto): self
    {
        $this->proyecto = $proyecto;

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setCiclo($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getCiclo() === $this) {
                $defecto->setCiclo(null);
            }
        }

        return $this;
    }

    public function getEstatusCiclo(): ?string
    {
        return $this->estatusCiclo;
    }

    public function setEstatusCiclo(?string $estatusCiclo): self
    {
        $this->estatusCiclo = $estatusCiclo;

        return $this;
    }

    public function getDuracionCiclos(): ?int
    {
        return $this->duracionCiclos;
    }

    public function setDuracionCiclos(?int $duracionCiclos): self
    {
        $this->duracionCiclos = $duracionCiclos;

        return $this;
    }

}

src/Entity/Defectos.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DefectosRepository")
 */
class Defectos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $asunto_defecto;

    /**
     * @ORM\Column(type="string", length=400, nullable=true)
     */
    private $descripcion_defecto;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_reportado;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $estatus;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nivel;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ciclos", inversedBy="defectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ciclo;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuarios", inversedBy="defectos")
     * @ORM\JoinColumn(nullable=true)
     */
    private $usuario;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $tester;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Proyectos", inversedBy="defectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $proyecto;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $tipo_defecto;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha_corregido;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $evidencia;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAsuntoDefecto(): ?string
    {
        return $this->asunto_defecto;
    }

    public function setAsuntoDefecto(string $asunto_defecto): self
    {
        $this->asunto_defecto = $asunto_defecto;

        return $this;
    }

    public function getDescripcionDefecto(): ?string
    {
        return $this->descripcion_defecto;
    }

    public function setDescripcionDefecto(?string $descripcion_defecto): self
    {
        $this->descripcion_defecto = $descripcion_defecto;

        return $this;
    }

    public function getFechaReportado(): ?\DateTimeInterface
    {
        return $this->fecha_reportado;
    }

    public function setFechaReportado(\DateTimeInterface $fecha_reportado): self
    {
        $this->fecha_reportado = $fecha_reportado;

        return $this;
    }

    public function getEstatus(): ?string
    {
        return $this->estatus;
    }

    public function setEstatus(string $estatus): self
    {
        $this->estatus = $estatus;

        return $this;
    }

    public function getNivel(): ?string
    {
        return $this->nivel;
    }

    public function setNivel(string $nivel): self
    {
        $this->nivel = $nivel;

        return $this;
    }

    public function getCiclo(): ?Ciclos
    {
        return $this->ciclo;
    }

    public function setCiclo(?Ciclos $ciclo): self
    {
        $this->ciclo = $ciclo;

        return $this;
    }

    public function getUsuario(): ?Usuarios
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuarios $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getTester(): ?string
    {
        return $this->tester;
    }

    public function setTester(string $tester): self
    {
        $this->tester = $tester;

        return $this;
    }

    public function getProyecto(): ?Proyectos
    {
        return $this->proyecto;
    }

    public function setProyecto(?Proyectos $proyecto): self
    {
        $this->proyecto = $proyecto;

        return $this;
    }

    public function getTipoDefecto(): ?string
    {
        return $this->tipo_defecto;
    }

    public function setTipoDefecto(string $tipo_defecto): self
    {
        $this->tipo_defecto = $tipo_defecto;

        return $this;
    }

    public function getFechaCorregido(): ?\DateTimeInterface
    {
        return $this->fecha_corregido;
    }

    public function setFechaCorregido(?\DateTimeInterface $fecha_corregido): self
    {
        $this->fecha_corregido = $fecha_corregido;

        return $this;
    }

    public function getEvidencia(): ?string
    {
        return $this->evidencia;
    }

    public function setEvidencia(?string $evidencia): self
    {
        $this->evidencia = $evidencia;

        return $this;
    }
}

src/Entity/Proyectos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProyectosRepository")
 */
class Proyectos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $clave_proyecto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_proyecto;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuarios", inversedBy="proyectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $responsable;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ciclos", mappedBy="proyecto")
     */
    private $ciclos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Defectos", mappedBy="proyecto")
     */
    private $defectos;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lenguage", inversedBy="proyectos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lenguage;

    public function __construct()
    {
        $this->ciclos = new ArrayCollection();
        $this->defectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClaveProyecto(): ?string
    {
        return $this->clave_proyecto;
    }

    public function setClaveProyecto(string $clave_proyecto): self
    {
        $this->clave_proyecto = $clave_proyecto;

        return $this;
    }

    public function getNombreProyecto(): ?string
    {
        return $this->nombre_proyecto;
    }

    public function setNombreProyecto(string $nombre_proyecto): self
    {
        $this->nombre_proyecto = $nombre_proyecto;

        return $this;
    }

    public function getResponsable(): ?Usuarios
    {
        return $this->responsable;
    }

    public function setResponsable(?Usuarios $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    /**
     * @return Collection|Ciclos[]
     */
    public function getCiclos(): Collection
    {
        return $this->ciclos;
    }

    public function addCiclo(Ciclos $ciclo): self
    {
        if (!$this->ciclos->contains($ciclo)) {
            $this->ciclos[] = $ciclo;
            $ciclo->setProyecto($this);
        }

        return $this;
    }

    public function removeCiclo(Ciclos $ciclo): self
    {
        if ($this->ciclos->contains($ciclo)) {
            $this->ciclos->removeElement($ciclo);
            // set the owning side to null (unless already changed)
            if ($ciclo->getProyecto() === $this) {
                $ciclo->setProyecto(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Defectos[]
     */
    public function getDefectos(): Collection
    {
        return $this->defectos;
    }

    public function addDefecto(Defectos $defecto): self
    {
        if (!$this->defectos->contains($defecto)) {
            $this->defectos[] = $defecto;
            $defecto->setProyecto($this);
        }

        return $this;
    }

    public function removeDefecto(Defectos $defecto): self
    {
        if ($this->defectos->contains($defecto)) {
            $this->defectos->removeElement($defecto);
            // set the owning side to null (unless already changed)
            if ($defecto->getProyecto() === $this) {
                $defecto->setProyecto(null);
            }
        }

        return $this;
    }

    public function getLenguage(): ?Lenguage
    {
        return $this->lenguage;
    }

    public function setLenguage(?Lenguage $lenguage): self
    {
        $this->lenguage = $lenguage;

        return $this;
    }
}

src/Controller/DefectosController.php
<?php

namespace App\Controller;

use App\Entity\Defectos;
use App\Form\DefectosType;
use App\Repository\DefectosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/defectos")
 */
class DefectosController extends AbstractController
{
    /**
     * @Route("/", name="defectos_index", methods={"GET"})
     */
    public function index(DefectosRepository $defectosRepository): Response
    {

        $pendientes = $defectosRepository->obtienePendientes();
        $bajos = $defectosRepository->obtieneBajos();
        $medios = $defectosRepository->obtieneMedios();
        $altos = $defectosRepository->obtieneAltos();
        $urgentes = $defectosRepository->obtieneUrgentes();


        return $this->render('defectos/index.html.twig', [
            'defectos' => $defectosRepository->findAll(),
            'pendientes' => $pendientes,
            'bajos' => $bajos,
            'medios' => $medios,
            'altos' => $altos,
            'urgentes' => $urgentes,
        ]);
    }

    /**
     * @Route("/new", name="defectos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $defecto = new Defectos();
        $form = $this->createForm(DefectosType::class, $defecto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($defecto);
            $entityManager->flush();

            return $this->redirectToRoute('defectos_index');
        }

        return $this->render('defectos/new.html.twig', [
            'defecto' => $defecto,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="defectos_show", methods={"GET"})
     */
    public function show(Defectos $defecto): Response
    {
        return $this->render('defectos/show.html.twig', [
            'defecto' => $defecto,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="defectos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Defectos $defecto): Response
    {
        $form = $this->createForm(DefectosType::class, $defecto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('defectos_index');
        }

        return $this->render('defectos/edit.html.twig', [
            'defecto' => $defecto,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="defectos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Defectos $defecto): Response
    {
        if ($this->isCsrfTokenValid('delete'.$defecto->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($defecto);
            $entityManager->flush();
        }

        return $this->redirectToRoute('defectos_index');
    }




}

templates/defectos/_delete_form.html.twig
<form method="post" action="{{ path('defectos_delete', {'id': defecto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ defecto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/defectos/_form.html.twig
{{ form_start(form) }}

<style>
    .form-group{
        margin-right: 20px;
        border-radius: 10px;
        border: 1px solid white;
        padding-bottom:8px;
        margin-bottom: 0px;
        font-weight: bold;
    }
    
    label{
        color:#455A64!important;
        padding-left: 10px;
    }
    
    #hallazgos_descripcion{
        height: 60px;
        padding-left:0px;
        margin-left: -10px;
    }
    
    .iconcalendar{
        margin-left:-20px;
        margin-top:26px;
        height: 34px;
    }
    .iconcalendar2{
        margin-left:31%;
        margin-top:26px;
        height: 34px;
        background-color: transparent;
        border:none;
    }
    #defectos_evidencia{
        width: 320%;
    }
    .form-group{
        border:none!important;
    }
    #defectos_asunto_defecto, #defectos_evidencia, #defectos_descripcion_defecto {
        font-size:12.5px;
    }

    .form-control{
        border-radius: 0px;
    }
    #basic-addon2{
        border:none;
    }
</style>

<div class="row" style="padding-left:17px; margin-right:16px;  font-size:12px;">
    {{form_row(form.tipo_defecto)}}
    
    {{ form_row(form.fecha_reportado) }}
    <div class="input-group-append iconcalendar">
        <span class="input-group-text" id="basic-addon2"><i class="far fa-calendar-alt"></i></span>
    </div>
</div>


<div style="padding-left:0px; width:50%;  font-size:12px;">
    {{form_row(form.asunto_defecto)}}
</div>


<div style="padding-left:0px; margin-right:6px;  font-size:12px;">
    {{ form_row(form.descripcion_defecto) }} 
</div>




<div class="row" style="padding-left:17px; margin-right:16px;  font-size:12px;">
    
    {{ form_row(form.proyecto) }}
    {{ form_row(form.ciclo) }} 
    {{ form_row(form.nivel) }} 
    {{ form_row(form.estatus) }} 
</div>

<div class="row" style="padding-left:17px; margin-right:16px;  font-size:12px;">

{{ form_row(form.tester) }} 
{{ form_row(form.usuario) }} 
{{ form_row(form.fecha_corregido) }} 
<div class="input-group-append iconcalendar">
        <span class="input-group-text" id="basic-addon2"><i class="far fa-calendar-alt"></i></span>
    </div>
</div>

<div class="row" style="padding-left:17px; font-size:12px;">
    {{ form_row(form.evidencia) }}
    <div class="input-group-append iconcalendar2">
            <span class="input-group-text" id="basic-addon2"><i class="fab fa-bitbucket"></i></span>
       </div>
</div>

<a class="btn" href="{{ path('defectos_index') }}" style="color:#2c3e50;"><i class="fas fa-chevron-left fa-2x"></i></a>
<button class="btn shadow" 
style="background-color:#2980b9; border:none; color:white; border-radius:0px; font-size:13.6px;">
{{ button_label|default('Guardar defecto') }}</button>



{{ form_end(form) }}

templates/defectos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Defectos{% endblock %}

{% block body %}
<div style="background-color:#78909C; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">
  <p style="font-size:14px; margin-bottom:4px;"> <i class="fas fa-project-diagram"></i>Edición de Defecto</p>
  
</div><br>

    <div class="container" style="padding-top:1px; border-left: 4px solid #2f245d;">

    {{ include('defectos/_form.html.twig', {'button_label': 'Actualizar defecto'}) }}

    {{ include('defectos/_delete_form.html.twig') }}


</div>
{% endblock %}

templates/defectos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Defectos{% endblock %}

{% block body %}
<div style="background-color:#78909C; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">
  <p style="font-size:14px; margin-bottom:4px;"> <i class="fas fa-project-diagram"></i>Reportar nuevo Defecto</p>
  
</div><br>

    <div class="container" style="padding-top:1px; border-left: 4px solid #2980b9;">
            <p style="font-size:12.5px; color:gray;"><strong> Datos que tendrá la incidencia a crear:</strong>  </p>
       
    {{ include('defectos/_form.html.twig') }}

  
    </div>
{% endblock %}

templates/defectos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Defectos{% endblock %}

{% block body %}
<style>
    th{
        width: 250px;
        color:gray;
        padding-left: 2px;
    }

</style>

<div style="background-color:#78909C; padding-right:10px; ;padding-top:3px; padding-bottom:1px; color:white; text-align:right;">
  <p style="font-size:14px; margin-bottom:4px;"> <i class="fas fa-project-diagram"></i>Datos del defecto seleccionado</p>
  
</div><br>
    <div class="container" style="padding-top:1px; border-left: 4px solid #2f245d; font-size:14px;">
            <p style="font-size:12.5px; color:gray;"><strong> Datos completos del Defecto:</strong>  </p>
    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ defecto.id }}</td>
            </tr>
            <tr>
                <th>Asunto</th>
                <td>{{ defecto.asuntoDefecto }}</td>
            </tr>
            <tr>
                <th>Descripción</th>
                <td>{{ defecto.descripcionDefecto }}</td>
            </tr>
            <tr>
                <th>Proyecto</th>
                <td>{{ defecto.proyecto.nombreProyecto }}</td>
            </tr>
            <tr>
                <th>Ciclo o Request</th>
                <td>{{ defecto.ciclo.nombreCiclo }}</td>
            </tr>
            <tr>
                <th>Fecha reportado</th>
                <td>{{ defecto.fechaReportado ? defecto.fechaReportado|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Estatus</th>
                <td>{{ defecto.estatus }}</td>
            </tr>
            <tr>
                <th>Nivel</th>
                <td>{{ defecto.nivel }}</td>
            </tr>
            <tr>
                <th>Tester</th>
                <td>{{ defecto.tester }}</td>
            </tr>
            <tr>
                <th>URL de evidencia</th>
                <td>{{ defecto.evidencia }}</td>
            </tr>
        </tbody>
    </table>

</i></a>
<a class="btn" href="{{ path('defectos_index') }}" style="color:#2c3e50;"><i class="fas fa-chevron-left fa-2x"></i></a>

  


    </div>
{% endblock %}